name: Lint
on:
  push

jobs:
  list_packages:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
    outputs:
      packages: ${{ steps.get-packages.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
      - name: Get package names
        id: get-packages
        run: |
          echo "packages=$(colcon list --names-only | jq -R -s -c 'split("\n")[:-1]')" >> "$GITHUB_ENV"

  ament_lint:
    needs: list_packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [xmllint, cpplint, uncrustify, pep257, flake8, mypy]
        package: ${{ fromJson(needs.list_packages.outputs.packages) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ros-tooling/action-ros-lint@v0.1
        with:
          linter: ${{ matrix.linter }}
          distribution: rolling
          package-name: ${{ matrix.package }}
